// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! JSON Schema generation for the public NeMo Fabric contract.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use schemars::schema_for;
use serde_json::Value;

use crate::config::{
    AdapterDescriptor, AdapterTargetDescriptor, AgentConfig, FabricConfig, RunPlan,
};
use crate::error::{FabricError, Result};
use crate::runtime::{
    AdapterInvocation, ArtifactManifest, EnvironmentHandle, ErrorInfo, FabricEvent,
    InvocationHandle, OpenAiStreamInvocation, OpenAiStreamRecord, RunRequest, RunResult,
    RuntimeContext, RuntimeHandle,
};
use crate::{AgentRunRequest, AgentRunResult};

/// Public schema snapshots generated by NeMo Fabric.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SchemaName {
    /// Complete typed NeMo Fabric config schema.
    Agent,
    /// Adapter-facing projected agent config schema.
    AgentConfig,
    /// Adapter-facing invocation request schema.
    AgentRunRequest,
    /// Adapter-facing terminal result schema.
    AgentRunResult,
    /// Adapter descriptor schema.
    AdapterDescriptor,
    /// Adapter target descriptor schema.
    AdapterTargetDescriptor,
    /// Resolved run plan schema.
    RunPlan,
    /// Initialized-runtime invocation payload schema.
    AdapterInvocation,
    /// Adapter-facing native OpenAI streaming invocation schema.
    OpenAiStreamInvocation,
    /// Adapter-native OpenAI streaming NDJSON record schema.
    OpenAiStreamRecord,
    /// Runtime context schema.
    RuntimeContext,
    /// Environment handle schema.
    EnvironmentHandle,
    /// Runtime handle schema.
    RuntimeHandle,
    /// Invocation handle schema.
    InvocationHandle,
    /// Runtime request schema.
    RunRequest,
    /// Runtime result schema.
    RunResult,
    /// Artifact manifest schema.
    ArtifactManifest,
    /// Structured error metadata schema.
    ErrorInfo,
    /// NeMo Fabric lifecycle event schema.
    FabricEvent,
}

impl SchemaName {
    /// All public schemas in stable output order.
    pub const ALL: [Self; 19] = [
        Self::Agent,
        Self::AgentConfig,
        Self::AgentRunRequest,
        Self::AgentRunResult,
        Self::AdapterDescriptor,
        Self::AdapterTargetDescriptor,
        Self::RunPlan,
        Self::AdapterInvocation,
        Self::OpenAiStreamInvocation,
        Self::OpenAiStreamRecord,
        Self::RuntimeContext,
        Self::EnvironmentHandle,
        Self::RuntimeHandle,
        Self::InvocationHandle,
        Self::RunRequest,
        Self::RunResult,
        Self::ArtifactManifest,
        Self::ErrorInfo,
        Self::FabricEvent,
    ];

    /// Stable file stem for this schema.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Agent => "agent",
            Self::AgentConfig => "agent-config",
            Self::AgentRunRequest => "agent-run-request",
            Self::AgentRunResult => "agent-run-result",
            Self::AdapterDescriptor => "adapter-descriptor",
            Self::AdapterTargetDescriptor => "adapter-target-descriptor",
            Self::RunPlan => "run-plan",
            Self::AdapterInvocation => "adapter-invocation",
            Self::OpenAiStreamInvocation => "openai-stream-invocation",
            Self::OpenAiStreamRecord => "openai-stream-record",
            Self::RuntimeContext => "runtime-context",
            Self::EnvironmentHandle => "environment-handle",
            Self::RuntimeHandle => "runtime-handle",
            Self::InvocationHandle => "invocation-handle",
            Self::RunRequest => "run-request",
            Self::RunResult => "run-result",
            Self::ArtifactManifest => "artifact-manifest",
            Self::ErrorInfo => "error-info",
            Self::FabricEvent => "fabric-event",
        }
    }

    /// Snapshot filename for this schema.
    pub fn filename(self) -> String {
        format!("{}.schema.json", self.as_str())
    }

    /// Snapshot path relative to the schema output directory.
    fn relative_path(self) -> PathBuf {
        let filename = self.filename();
        match self {
            Self::AgentConfig
            | Self::AgentRunRequest
            | Self::AgentRunResult
            | Self::AdapterDescriptor
            | Self::AdapterTargetDescriptor
            | Self::AdapterInvocation
            | Self::OpenAiStreamInvocation
            | Self::OpenAiStreamRecord
            | Self::RuntimeContext => PathBuf::from("adapter-contract").join(filename),
            _ => PathBuf::from("sdk").join(filename),
        }
    }

    /// Parse a schema name from CLI/user input.
    pub fn parse(value: &str) -> Result<Self> {
        match value {
            "agent" => Ok(Self::Agent),
            "agent-config" | "agent_config" => Ok(Self::AgentConfig),
            "agent-run-request" | "agent_run_request" => Ok(Self::AgentRunRequest),
            "agent-run-result" | "agent_run_result" => Ok(Self::AgentRunResult),
            "adapter-descriptor" | "adapter_descriptor" => Ok(Self::AdapterDescriptor),
            "adapter-target-descriptor" | "adapter_target_descriptor" => {
                Ok(Self::AdapterTargetDescriptor)
            }
            "run-plan" | "run_plan" => Ok(Self::RunPlan),
            "adapter-invocation" | "adapter_invocation" => Ok(Self::AdapterInvocation),
            "openai-stream-invocation" | "openai_stream_invocation" => {
                Ok(Self::OpenAiStreamInvocation)
            }
            "openai-stream-record" | "openai_stream_record" => Ok(Self::OpenAiStreamRecord),
            "runtime-context" | "runtime_context" => Ok(Self::RuntimeContext),
            "environment-handle" | "environment_handle" => Ok(Self::EnvironmentHandle),
            "runtime-handle" | "runtime_handle" => Ok(Self::RuntimeHandle),
            "invocation-handle" | "invocation_handle" => Ok(Self::InvocationHandle),
            "run-request" | "run_request" => Ok(Self::RunRequest),
            "run-result" | "run_result" => Ok(Self::RunResult),
            "artifact-manifest" | "artifact_manifest" => Ok(Self::ArtifactManifest),
            "error-info" | "error_info" => Ok(Self::ErrorInfo),
            "fabric-event" | "fabric_event" => Ok(Self::FabricEvent),
            _ => Err(FabricError::UnknownSchema {
                schema: value.to_string(),
                available: Self::ALL
                    .iter()
                    .map(|schema| schema.as_str().to_string())
                    .collect(),
            }),
        }
    }
}

/// Generate one schema as a JSON value.
pub fn generate_schema(schema: SchemaName) -> Result<Value> {
    match schema {
        SchemaName::Agent => to_value(schema_for!(FabricConfig)),
        SchemaName::AgentConfig => to_value(schema_for!(AgentConfig)),
        SchemaName::AgentRunRequest => to_value(schema_for!(AgentRunRequest)),
        SchemaName::AgentRunResult => to_value(schema_for!(AgentRunResult)),
        SchemaName::AdapterDescriptor => to_value(schema_for!(AdapterDescriptor)),
        SchemaName::AdapterTargetDescriptor => to_value(schema_for!(AdapterTargetDescriptor)),
        SchemaName::RunPlan => to_value(schema_for!(RunPlan)),
        SchemaName::AdapterInvocation => to_value(schema_for!(AdapterInvocation)),
        SchemaName::OpenAiStreamInvocation => to_value(schema_for!(OpenAiStreamInvocation)),
        SchemaName::OpenAiStreamRecord => to_value(schema_for!(OpenAiStreamRecord)),
        SchemaName::RuntimeContext => to_value(schema_for!(RuntimeContext)),
        SchemaName::EnvironmentHandle => to_value(schema_for!(EnvironmentHandle)),
        SchemaName::RuntimeHandle => to_value(schema_for!(RuntimeHandle)),
        SchemaName::InvocationHandle => to_value(schema_for!(InvocationHandle)),
        SchemaName::RunRequest => to_value(schema_for!(RunRequest)),
        SchemaName::RunResult => to_value(schema_for!(RunResult)),
        SchemaName::ArtifactManifest => to_value(schema_for!(ArtifactManifest)),
        SchemaName::ErrorInfo => to_value(schema_for!(ErrorInfo)),
        SchemaName::FabricEvent => to_value(schema_for!(FabricEvent)),
    }
}

/// Generate all schemas keyed by stable schema name.
pub fn generate_all_schemas() -> Result<BTreeMap<String, Value>> {
    SchemaName::ALL
        .iter()
        .map(|schema| Ok((schema.as_str().to_string(), generate_schema(*schema)?)))
        .collect()
}

/// Generate one schema as pretty JSON.
pub fn generate_schema_json(schema: SchemaName) -> Result<String> {
    serde_json::to_string_pretty(&generate_schema(schema)?).map_err(FabricError::SerializeJson)
}

/// Write all schema snapshots to `directory`.
pub fn write_schema_snapshots(directory: impl AsRef<Path>) -> Result<Vec<PathBuf>> {
    let directory = directory.as_ref();
    std::fs::create_dir_all(directory).map_err(|source| FabricError::Write {
        path: directory.to_path_buf(),
        source,
    })?;
    let mut written = Vec::new();
    for schema in SchemaName::ALL {
        let path = directory.join(schema.relative_path());
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|source| FabricError::Write {
                path: parent.to_path_buf(),
                source,
            })?;
        }
        std::fs::write(&path, generate_schema_json(schema)?).map_err(|source| {
            FabricError::Write {
                path: path.clone(),
                source,
            }
        })?;
        written.push(path);
    }
    Ok(written)
}

fn to_value<T>(schema: T) -> Result<Value>
where
    T: serde::Serialize,
{
    serde_json::to_value(schema).map_err(FabricError::SerializeJson)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::TelemetryProvider;

    fn schema_dir() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../schemas")
    }

    #[test]
    fn schema_snapshots_match_generated_contract() {
        for schema in SchemaName::ALL {
            let path = schema_dir().join(schema.relative_path());
            let expected: Value = serde_json::from_str(
                &std::fs::read_to_string(&path)
                    .unwrap_or_else(|error| panic!("failed to read {}: {error}", path.display())),
            )
            .unwrap_or_else(|error| panic!("failed to parse {}: {error}", path.display()));
            let generated = generate_schema(schema).expect("schema generation");

            assert_eq!(generated, expected, "schema snapshot drifted: {schema:?}");
        }
    }

    #[test]
    fn all_schemas_are_available_by_stable_name() {
        let schemas = generate_all_schemas().expect("schema generation");

        for schema in SchemaName::ALL {
            assert!(schemas.contains_key(schema.as_str()), "missing {schema:?}");
            assert_eq!(
                SchemaName::parse(schema.as_str()).expect("known schema"),
                schema
            );
        }
    }

    #[test]
    fn schemas_use_contract_boundary_snapshot_paths() {
        for schema in [
            SchemaName::AdapterDescriptor,
            SchemaName::AgentConfig,
            SchemaName::AgentRunRequest,
            SchemaName::AgentRunResult,
            SchemaName::AdapterInvocation,
            SchemaName::OpenAiStreamInvocation,
            SchemaName::OpenAiStreamRecord,
            SchemaName::RuntimeContext,
        ] {
            assert_eq!(
                schema.relative_path(),
                PathBuf::from("adapter-contract").join(schema.filename())
            );
        }
        for schema in [
            SchemaName::Agent,
            SchemaName::RunPlan,
            SchemaName::EnvironmentHandle,
            SchemaName::RuntimeHandle,
            SchemaName::InvocationHandle,
            SchemaName::RunRequest,
            SchemaName::RunResult,
            SchemaName::ArtifactManifest,
            SchemaName::ErrorInfo,
            SchemaName::FabricEvent,
        ] {
            assert_eq!(
                schema.relative_path(),
                PathBuf::from("sdk").join(schema.filename())
            );
        }
    }

    #[test]
    fn agent_schema_enforces_positive_invocation_limits() {
        let schema = generate_schema(SchemaName::Agent).expect("schema generation");

        assert_eq!(
            schema["$defs"]["InstructionConfig"]["properties"]["content"]["minLength"],
            1
        );
        assert_eq!(
            schema["$defs"]["InstructionConfig"]["properties"]["content"]["pattern"],
            r"\S"
        );
        assert_eq!(
            schema["$defs"]["EnvironmentConfig"]["properties"]["env"]["propertyNames"]["pattern"],
            r"\S"
        );
        assert_eq!(
            schema["$defs"]["RuntimeConfig"]["properties"]["max_turns"]["minimum"],
            1
        );
        assert_eq!(
            schema["$defs"]["RuntimeConfig"]["properties"]["max_turns"]["maximum"],
            u32::MAX
        );
        assert_eq!(
            schema["$defs"]["RuntimeConfig"]["properties"]["timeout_seconds"]["exclusiveMinimum"],
            0.0
        );
        assert_eq!(
            schema["$defs"]["McpAuthenticationConfig"]["oneOf"][0]["properties"]["authorization_timeout_seconds"]
                ["minimum"],
            1
        );
    }

    #[test]
    fn openai_stream_schemas_freeze_transport_and_record_invariants() {
        let invocation =
            generate_schema(SchemaName::OpenAiStreamInvocation).expect("schema generation");
        let sink = &invocation["$defs"]["OpenAiStreamSink"];
        assert_eq!(sink["properties"]["port"]["minimum"], 1);
        assert_eq!(sink["properties"]["token"]["minLength"], 1);
        assert_eq!(
            sink["properties"]["token"]["pattern"],
            r"^[^\r\n]*\S[^\r\n]*$"
        );
        assert_eq!(
            invocation["$defs"]["OpenAiStreamProtocolVersion"]["oneOf"][0]["const"],
            crate::runtime::OPENAI_STREAM_PROTOCOL_VERSION
        );
        assert_eq!(
            invocation["$defs"]["OpenAiStreamProfile"]["oneOf"][0]["const"],
            crate::runtime::OPENAI_CHAT_COMPLETIONS_CHUNK_PROFILE
        );
        assert_eq!(
            invocation["$defs"]["OpenAiStreamHost"]["oneOf"][0]["const"],
            crate::runtime::OPENAI_STREAM_HOST
        );

        let record = generate_schema(SchemaName::OpenAiStreamRecord).expect("schema generation");
        assert_eq!(record["oneOf"][0]["properties"]["type"]["const"], "chunk");
        assert_eq!(record["oneOf"][1]["properties"]["type"]["const"], "end");
        assert_eq!(record["oneOf"][0]["additionalProperties"], false);
        assert_eq!(record["oneOf"][1]["additionalProperties"], false);
        assert_eq!(
            record["oneOf"][0]["properties"]["sequence"]["maximum"],
            u64::MAX
        );
        assert_eq!(
            record["oneOf"][1]["properties"]["sequence"]["maximum"],
            u64::MAX
        );
        assert_eq!(
            record["$defs"]["OpenAiChatCompletionChunk"]["required"],
            serde_json::json!(["id", "object", "created", "model", "choices"])
        );
        assert_eq!(
            record["$defs"]["OpenAiChatCompletionChunk"]["properties"]["created"]["maximum"],
            u64::MAX
        );
        assert_eq!(
            record["$defs"]["OpenAiChatCompletionChunkObject"]["oneOf"][0]["const"],
            "chat.completion.chunk"
        );
    }

    #[test]
    fn adapter_descriptor_schema_matches_runtime_constraints() {
        let schema = generate_schema(SchemaName::AdapterDescriptor).expect("schema generation");

        assert_eq!(
            schema["properties"]["contract_version"]["const"],
            crate::ADAPTER_CONTRACT_VERSION
        );
        assert_eq!(schema["properties"]["contract_version"]["minLength"], 1);
        assert_eq!(schema["properties"]["adapter_id"]["minLength"], 1);
        assert_eq!(schema["properties"]["adapter_id"]["pattern"], r"\S");
        assert_eq!(
            schema["properties"]["settings_schema"]["type"],
            serde_json::json!(["object", "null"])
        );
        assert_eq!(
            schema["properties"]["model_schema"]["type"],
            serde_json::json!(["object", "null"])
        );
        assert!(schema["properties"]["target_types"].is_object());
        assert_eq!(
            schema["properties"]["extension_schemas"]["propertyNames"]["enum"],
            serde_json::json!([
                "agent_config",
                "harness",
                "model",
                "instructions",
                "instruction",
                "runtime",
                "skills",
                "mcp",
                "mcp_server",
                "tools",
                "tool_definition",
                "workflow",
                "workflow_entrypoint",
                "run_request",
                "run_result",
                "run_error",
                "artifact",
                "usage"
            ])
        );
        let declared_providers = &schema["$defs"]["AdapterTelemetrySupport"]["properties"]["providers"]
            ["propertyNames"]["enum"];
        assert_eq!(declared_providers, &serde_json::json!(["relay", "native"]));
        let provider_schema =
            serde_json::to_value(schema_for!(TelemetryProvider)).expect("provider schema");
        let derived_providers = Value::Array(
            provider_schema["oneOf"]
                .as_array()
                .expect("provider variants")
                .iter()
                .map(|variant| variant["const"].clone())
                .collect(),
        );
        assert_eq!(
            declared_providers, &derived_providers,
            "TelemetryProvider::ALL must include every enum variant"
        );

        let validator = jsonschema::validator_for(&schema).expect("valid descriptor schema");
        let descriptor = serde_json::json!({
            "contract_version": crate::ADAPTER_CONTRACT_VERSION,
            "adapter_id": "test.fabric.schema",
            "adapter_kind": "python",
            "telemetry": {
                "providers": {
                    "relay": {}
                }
            }
        });
        assert!(validator.is_valid(&descriptor));

        let mut unsupported_contract = descriptor.clone();
        unsupported_contract["contract_version"] = serde_json::json!("fabric.adapter/v1alpha3");
        assert!(!validator.is_valid(&unsupported_contract));

        let mut unsupported_provider = descriptor.clone();
        unsupported_provider["telemetry"]["providers"] = serde_json::json!({"custom": {}});
        assert!(!validator.is_valid(&unsupported_provider));

        for field in ["adapter_id"] {
            let mut blank_identifier = descriptor.clone();
            blank_identifier[field] = serde_json::json!(" \t");
            assert!(!validator.is_valid(&blank_identifier));
        }
    }

    #[test]
    fn adapter_contract_schemas_bound_rust_integer_types() {
        let config = generate_schema(SchemaName::AgentConfig).expect("schema generation");
        for field in ["provider", "model"] {
            assert_eq!(
                config["$defs"]["AgentModelConfig"]["properties"][field]["pattern"],
                r"\S"
            );
        }
        assert_eq!(
            config["$defs"]["AgentRuntimeConfig"]["properties"]["max_turns"]["maximum"],
            u32::MAX
        );

        let result = generate_schema(SchemaName::AgentRunResult).expect("schema generation");
        for field in ["input_tokens", "output_tokens", "total_tokens"] {
            assert_eq!(
                result["$defs"]["AgentUsage"]["properties"][field]["maximum"],
                u64::MAX
            );
        }
    }

    #[test]
    fn adapter_target_descriptor_schema_matches_runtime_constraints() {
        let schema =
            generate_schema(SchemaName::AdapterTargetDescriptor).expect("schema generation");

        assert_eq!(
            schema["properties"]["contract_version"]["const"],
            crate::ADAPTER_CONTRACT_VERSION
        );
        assert_eq!(schema["properties"]["id"]["minLength"], 1);
        assert_eq!(schema["properties"]["id"]["pattern"], r"\S");
        assert_eq!(schema["properties"]["adapter_id"]["minLength"], 1);
        assert_eq!(schema["properties"]["adapter_id"]["pattern"], r"\S");
        assert_eq!(
            schema["$defs"]["WorkflowTargetSpec"]["properties"]["settings_schema"]["type"],
            serde_json::json!(["object", "null"])
        );
    }

    #[test]
    fn agent_run_result_schema_enforces_failure_and_artifact_invariants() {
        let schema = generate_schema(SchemaName::AgentRunResult).expect("schema generation");
        let validator = jsonschema::validator_for(&schema).expect("valid result schema");

        assert!(!validator.is_valid(&serde_json::json!({
            "status": "failed",
            "output": null
        })));
        assert!(!validator.is_valid(&serde_json::json!({
            "status": "succeeded",
            "output": null,
            "error": {"code": "target_error", "message": "target failed"}
        })));
        assert!(validator.is_valid(&serde_json::json!({
            "status": "succeeded",
            "output": null
        })));
        assert!(validator.is_valid(&serde_json::json!({
            "status": "succeeded",
            "output": null,
            "error": null
        })));
        for path in [
            " \t",
            "nested/../output",
            r"nested\..\output",
            r"C:\tmp\output",
            r"C:output",
            r"\\server\output",
        ] {
            assert!(!validator.is_valid(&serde_json::json!({
                "status": "succeeded",
                "output": null,
                "artifacts": [{
                    "name": "output",
                    "kind": "file",
                    "path": path
                }]
            })));
        }
        assert!(!validator.is_valid(&serde_json::json!({
            "status": "succeeded",
            "output": null,
            "artifacts": [{
                "name": "output",
                "kind": "file",
                "path": "/tmp/output"
            }]
        })));
        assert!(validator.is_valid(&serde_json::json!({
            "status": "failed",
            "output": null,
            "error": {"code": "target_error", "message": "target failed"}
        })));
    }
}
